import os
from github_utils import GitHubIntegration
from docker_env import DockerSandbox
from agent_graph import AutoDevGraph

def main():
    print("🚀 Initializing AutoDev Autonomous SWE Agent 🚀\n")
    
    # 1. Fetch GitHub Issue
    gh = GitHubIntegration()
    repo_name = "Muhammad08-dot/sample-repo"
    issue = gh.fetch_issue(repo_name, 1)
    
    issue_text = issue.get("title", "Fix memory leak in data parser")
    
    # 2. Start Docker Sandbox
    sandbox = DockerSandbox()
    sandbox.start_sandbox(workspace_path="./workspace")
    
    # 3. Run Agent Graph
    graph = AutoDevGraph()
    final_state = graph.run(issue_text)
    
    # 4. Clean up Sandbox
    sandbox.teardown()
    
    # 5. Create PR if successful
    if final_state.get("success"):
        gh.create_pull_request(
            repo_name=repo_name,
            branch="autodev/fix-memory-leak",
            title="Automated Fix: Memory Leak",
            body="This PR was autonomously generated by AutoDev after passing all tests in Docker."
        )

if __name__ == "__main__":
    main()
